require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lualine-config"
require "user.bufferline-config"
require "user.nvimtree-config"
require "user.cmp-config"
require "user.toggleterm-config"
require "user.treesitter-config"
require "user.telescope-config"
require "user.lsp"
require "user.whichkey-config"
require "user.comment-config"
require "user.alpha-config"
require "user.hop-config"
require "user.autopairs-config"
require "user.autotag-config"

vim.cmd "colorscheme darcula-solid"

